# Generated by Django 5.1.5 on 2025-02-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_data', '0002_property_user_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image_path', models.CharField(max_length=250)),
                ('rate_buy', models.FloatField()),
                ('rate_lease', models.FloatField()),
                ('floor', models.IntegerField()),
                ('unit_no', models.CharField(max_length=50)),
                ('wing', models.CharField(max_length=50)),
                ('car_parking', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('property_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='property_data.property')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='user.ariyanspropertiesuser')),
            ],
            options={
                'db_table': 'property_details',
            },
        ),
    ]
