# Generated by Django 5.1.5 on 2025-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_code', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('des_code', models.CharField(blank=True, max_length=100, null=True)),
                ('lease_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('usp', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person1', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person2', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person3', models.CharField(blank=True, max_length=100, null=True)),
                ('c_status', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
    ]
